###
GET http://localhost:3333/telehealth/products

###
GET http://localhost:3333/telehealth/products/67a08e15d6b3a72f38d48f2d

###
POST http://localhost:3333/telehealth/products HTTP/1.1
content-type: application/json

{
    "postOfficeBox": "Rajiv Gandhi"
}

###
PUT http://localhost:3333/telehealth/products/67a08e15d6b3a72f38d48f2d HTTP/1.1
content-type: application/json

{
    "postOfficeBox": "Rajiv Gandhi Circle"
}

###
DELETE http://localhost:3333/telehealth/products/67a08a8baa708f05a6a380e1